### ISSUE TITLE
cose da fare

### ISSUE THREAD

**Issue by Donerio** [Donerio/IGIENE#1]
- [x]  13

- [x]   14

- [x]   15

- [x]    16

queste prima quattro formano una SEZIONE chiamata  ORGANIZZAZIONE SSN ED ECONOMIA AZIENDALE

- [x]   17

- [x]   18

Queste due sopra formano una SEZIONE chiamata DETERMINANTI DI SALUTE

- [x]   19

questa SEZIONE chiamata INFEZIONI CORRELATE ALL ASSISTENZA

- [x]   20

questa SEZIONE chiamata HACCP e nutrizione

- [x]   21

questa SEZIONE chiamata PREVENZIONE E SCREENING

- [x]   22

- [x]   23  (Questa è ancora da caricare)

- [x]   24

Queste ultime tre SEZIONE chiamata AMBIENTE E SALUTE

- [x]  25

Quest'ultima SEZIONE chiamata ESEMPI QUIZ SECONDO PARZIALE

**Comment by graziab** [comment]
B
